version: '3.8'

services:
  postgres:
    build: ./services/postgres
    container_name: postgres-northwind
    ports:
      - "5432:5432"
    env_file:
      - ./services/postgres/configs/postgres.env
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    volumes:
      - pg_data:/var/lib/postgresql/data

  zookeeper:
    build: ./services/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - ./services/zookeeper/configs/zookeeper.env

  kafka:
    build: ./services/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - ./services/kafka/configs/kafka.env
    depends_on:
      - zookeeper

  schema-registry:
    build: ./services/schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
    env_file:
      - ./services/schema-registry/configs/schema-registry.env
    depends_on:
      - kafka

  kafka-connect:
    build: ./services/kafka-connect
    container_name: kafka-connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - schema-registry
    env_file:
      - ./services/schema-registry/configs/schema-registry.env
    volumes:
      - ./services/kafka-connect/kafka-connect-plugins:/etc/kafka-connect/jars
      - ./services/kafka-connect/connectors:/etc/kafka-connect/connectors
      - ./services/kafka-connect/scripts:/etc/kafka-connect/scripts 
    command: >
      sh -c "/etc/kafka-connect/scripts/create-connect-topics.sh &&
            sleep 5 &&
            exec /etc/confluent/docker/run"

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "8080:8080"
    volumes:
      - ./services/akhq/configs/application.yml:/app/application.yml
    depends_on:
      - kafka

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # web console
   
    env_file:
      - ./services/minio/configs/minio.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
